### ISSUE TITLE
Form load error when no GPUs are configured

### ISSUE THREAD

**Issue by dnhodgson** [cmd-ntrf/slurmformspawner#13]
when no GPUs are configured for the cluster the form fails with a 500 error.

```
May 18 15:03:17 ctld0 jupyterhub: Traceback (most recent call last):
May 18 15:03:17 ctld0 jupyterhub: File "/opt/jupyterhub/lib64/python3.6/site-packages/tornado/web.py", line 1703, in _execute
May 18 15:03:17 ctld0 jupyterhub: result = await result
May 18 15:03:17 ctld0 jupyterhub: File "/opt/jupyterhub/lib64/python3.6/site-packages/jupyterhub/handlers/pages.py", line 186, in get
May 18 15:03:17 ctld0 jupyterhub: spawner_options_form = await spawner.get_options_form()
May 18 15:03:17 ctld0 jupyterhub: File "/opt/jupyterhub/lib64/python3.6/site-packages/jupyterhub/spawner.py", line 352, in get_options_form
May 18 15:03:17 ctld0 jupyterhub: if callable(self.options_form):
May 18 15:03:17 ctld0 jupyterhub: File "/opt/jupyterhub/lib64/python3.6/site-packages/slurmformspawner/spawner.py", line 103, in options_form
May 18 15:03:17 ctld0 jupyterhub: return self.form.render()
May 18 15:03:17 ctld0 jupyterhub: File "/opt/jupyterhub/lib64/python3.6/site-packages/slurmformspawner/form.py", line 171, in render
May 18 15:03:17 ctld0 jupyterhub: return Template(self.template).render(form=self.form)
May 18 15:03:17 ctld0 jupyterhub: File "/opt/jupyterhub/lib64/python3.6/site-packages/jinja2/environment.py", line 1090, in render
May 18 15:03:17 ctld0 jupyterhub: self.environment.handle_exception()
May 18 15:03:17 ctld0 jupyterhub: File "/opt/jupyterhub/lib64/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
May 18 15:03:17 ctld0 jupyterhub: reraise(*rewrite_traceback_stack(source=source))
May 18 15:03:17 ctld0 jupyterhub: File "/opt/jupyterhub/lib64/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
May 18 15:03:17 ctld0 jupyterhub: raise value.with_traceback(tb)
May 18 15:03:17 ctld0 jupyterhub: File "<template>", line 42, in top-level template code
May 18 15:03:17 ctld0 jupyterhub: File "/opt/jupyterhub/lib64/python3.6/site-packages/wtforms/fields/core.py", line 160, in __call__
May 18 15:03:17 ctld0 jupyterhub: return self.meta.render_field(self, kwargs)
May 18 15:03:17 ctld0 jupyterhub: File "/opt/jupyterhub/lib64/python3.6/site-packages/wtforms/meta.py", line 56, in render_field
May 18 15:03:17 ctld0 jupyterhub: return field.widget(field, **render_kw)
May 18 15:03:17 ctld0 jupyterhub: File "/opt/jupyterhub/lib64/python3.6/site-packages/wtforms/widgets/core.py", line 300, in __call__
May 18 15:03:17 ctld0 jupyterhub: for val, label, selected in field.iter_choices():
May 18 15:03:17 ctld0 jupyterhub: File "/opt/jupyterhub/lib64/python3.6/site-packages/wtforms/fields/core.py", line 481, in iter_choices
May 18 15:03:17 ctld0 jupyterhub: elif isinstance(self.choices[0], (list, tuple)):
```

I confirmed that self.form does have the correct looking info (`dict_items([('gpu:0', 'None')])`) in self.form from:

```
May 18 15:03:17 ctld0 jupyterhub: File "/opt/jupyterhub/lib64/python3.6/site-packages/slurmformspawner/form.py", line 171, in render
May 18 15:03:17 ctld0 jupyterhub: return Template(self.template).render(form=self.form)
```

However by the time it gets to the end the first item in the list is removed. The following is from some logging in 

```
May 18 15:03:17 ctld0 jupyterhub: File "/opt/jupyterhub/lib64/python3.6/site-packages/wtforms/fields/core.py", line 481, in iter_choices
May 18 15:03:17 ctld0 jupyterhub: elif isinstance(self.choices[0], (list, tuple)):
```

```
[('', 'None')]
[('users', 'users')]
[('', 'None')]
[('users', 'users')]
```

Removing the following from the template file fixes the problem
```
 {{ form.gpus(class_="form-control") }}
```

**Comment by cmd-ntrf** [comment]
Does this happen with v2.1.1?

**Comment by dnhodgson** [comment]
I am pulling from master. Looks like the code from that commit matched what I have.

**Comment by dnhodgson** [comment]
Confirmed 2.1.1 resolved this issue.
